"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['FlappyBird.py']
DATA_FILES = ['background-night.png', 'bluebird-midflap.png', 'bluebird-upflap.png', 'bluebird-downflap.png', 'base.png', 'pipe-green.png', 'sfx_hit.wav', 'sfx_point.wav', 'sfx_point.wav', 'sfx_wing.wav']
OPTIONS = {'argv_emulation': True,
'packages':['pygame']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
